# Ensure this is at the very beginning of the file, no leading spaces
steps:
  - name: 'gcr.io/cloud-builders/docker' # Indented with 2 spaces (or more, but consistently)
    args: [ # 'args' is at the same indentation level as 'name'
      'build',
      '-t', 'gcr.io/$PROJECT_ID/n8n:latest',
      '-f', 'docker/images/n8n/Dockerfile',
      '.'
    ] # Closing bracket for args

images: # Same indentation level as 'steps'
  - 'gcr.io/$PROJECT_ID/n8n:latest' # Indented list item

logsBucket: 'gs://dronemapper-43d80-cloudbuild-logs' # Same indentation level as 'steps' and 'images'
