 ```yaml
 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: [
     'build',
     '-t', 'gcr.io/$PROJECT_ID/n8n:latest',  # Or your desired image name/tag
     '-f', 'docker/images/n8n/Dockerfile',   # Path to your n8n Dockerfile
     '.'
   ]
 images:
 - 'gcr.io/$PROJECT_ID/n8n:latest' # Should match the -t argument
 logsBucket: 'gs://dronemapper-43d80-cloudbuild-logs' # <<< THIS IS THE CRUCIAL ADDITION/CHANGE
 ```
