steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/n8n:latest',
      '-f', 'docker/images/n8n/Dockerfile',
      '.'
    ]
    env: # Add this section
      - 'DOCKER_BUILDKIT=1' # Enable BuildKit

images:
  - 'gcr.io/$PROJECT_ID/n8n:latest'

logsBucket: 'gs://dronemapper-43d80-cloudbuild-logs'
